### ISSUE TITLE
Chell failed restore stock firmware using downloaded shellball firmware

### ISSUE THREAD

**Issue by foxog** [MrChromebox/scripts#96]
I tried to intsall windows10 on my chromebook 13 G1,but since unplug power cable will case crash, So I tried to restore stock firmware .
    Using ubuntu 18.04 livecd ,and run this script ,choose download firmware ,then reboot ,and it bricked :( .Screen is black,keyboard backlight worked,but caps lock(using external keyboard)doesn't work.
    By using usb flash programmer(and firmware from online firmware seller),I successed unbricking,but It takes 30s to light up srceen and boot up,using flashrom flash firmware from another chell,didn't work.
    So I decide to install costom firmware using this script,but it still take 30s to light up screen.
    Finally, I try to restore stock firmware by using dowloaded firmware,and it bricked,again.
    I think there is something wrong with the downloaded shellball firmware,or it's not compatible with this device.
    More info about this device CPU 4405Y Screen RES 3200*1800 Memory 4GB

**Comment by MrChromebox** [comment]
not sure why you'd have issues, works fine on my chell here with exact same config (Pentium 4405Y/4GB/32GB/1800p). I'll take a look into updating it in case it's been superseded

**Comment by MrChromebox** [comment]
just checked chell's shellball, and Google had updated it, so I pushed the new version.  Give it a go and let me know if it now works. Looking at the commit history, it seems they did add/update support for certain RAM types, so possible your device uses one of those

**Comment by foxog** [comment]
> just checked chell's shellball, and Google had updated it, so I pushed the new version. Give it a go and let me know if it now works. Looking at the commit history, it seems they did add/update support for certain RAM types, so possible your device uses one of those
    (I want to use it for some days before it bricked again,and these are informations about this unbricking)
    9 days ago after I successed unbricking,I tried to use `sudo flashrom -r bios.rom` to get stock firmware from another chell(1080p ver),and use `sudo flashrom -w bios.rom`,it didn't bricked,but also didn't fix the '30s-boot-up'* problem.
    But today I tried to use the same firmware and usb programmer to unbricking,it still bricked (and even worse,the keybroad backlight didn't turn on when power cable is pluged in)(custom firmware also didn't work)
     I had to use the firmware I bought last time to unbircking and It worked(it still takes 30s before bootup,and this time it shows "Your system is applying a critical update.Please do not turn it off" when booting up). 
    So maybe there is some difference between `flashrom` and usb programmer(both read and write).the `flashrom` only read/write some part of firmware falsh chip,and it cause compatible issues when you using firmware from different source,or just because this chell have some hardware problem...

   *'30s-boot-up' is very similar to https://www.youtube.com/watch?v=IJIsH-SDI8k

**Comment by MrChromebox** [comment]
first boot after flashing always takes longer, since the device must perform RAM training.

flashing an image using an external programmer that was read from a live system via flashrom -r will not work, because the image is missing parts that cannot be read when the system is booted.

please use an external programmer to flash the updated shellball ROM, and report how it works subsequent to the initial boot
